#Configuration are kept here and not environmental variable.

server:
  port: 8082

spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: admin
    url: jdbc:mysql://localhost:3306/Uber_DB_Local
    username: root
  jpa:
    hibernate:
      ddl-auto: update   #create  #validate.
    show-sql: true
welcome:
  message: db migration not done yet!!


#  flyway:
#    enabled: true
#    url: jdbc:mysql://localhost:3306/Uber_DB_Local
#    user: root
#    password: admin
#    baselineOnMigrate: true
#    validateOnMigrate: false
##    baseline-on-migrate: true
##    locations: classpath:db/migration   Optional, default is classpath:db/migration


